version: '3.5'

services:

# Custom services.
  # db:
  #   image: postgres:11.5
  #   environment:
  #     POSTGRES_USER: dev
  #     POSTGRES_PASSWORD: FinchDev
  #     POSTGRES_MULTIPLE_DATABASES: "\"pact-broker\",\"chat\""
  #   volumes:
  #     - dbdata:/var/lib/postgresql/data
  #     - ./scripts/startup:/docker-entrypoint-initdb.d
  #   ports:
  #     - 4261:5432
  #   networks:
  #     - dev_default

  chat:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: dev
      DB_DBNAME: chat
      DB_PASSWORD: FinchDev
      SERVICE_HOST: 0.0.0.0
      SERVICE_PORT: 8080
    ports:
      - 4265:8080
    networks:
      - dev_default

# volumes:
#   dbdata:

networks:
  dev_default:
    external: true
    name: finch_dev_default

#192.168.1.10