apiVersion: v1
kind: ConfigMap
metadata:
  name: go-api-config
  labels:
    app: go-api
data:
  DB_HOST: db
  DB_PORT: "5432"
  DB_USER: dev
  DB_DBNAME: chat
  DB_PASSWORD: FinchDev
  SERVICE_HOST: 0.0.0.0
  SERVICE_PORT: "8080"
